import Foundation
import Testing

@testable import KanbanCodeCore

/// The chat reads one file five different ways: the tail for what is on
/// screen, appended bytes for what just happened, a backward scan for the
/// previous typed message, a bounded range for a collapsed stretch, and a
/// count for the line standing in for one. They are only interchangeable if
/// every one of them names a turn by the byte offset its line starts at and
/// filters lines the same way.
@Suite("Transcript window reading")
struct TranscriptWindowTests {

    // MARK: - Fixture

    private static func json(_ payload: [String: Any]) -> String {
        let data = try! JSONSerialization.data(withJSONObject: payload)
        return String(data: data, encoding: .utf8)!
    }

    private static func user(_ text: String) -> String {
        json([
            "type": "user",
            "message": ["role": "user", "content": [["type": "text", "text": text]]],
        ])
    }

    private static func assistant(_ text: String) -> String {
        json([
            "type": "assistant",
            "message": ["role": "assistant", "content": [["type": "text", "text": text]]],
        ])
    }

    private static func assistantTool(_ command: String) -> String {
        json([
            "type": "assistant",
            "message": [
                "role": "assistant",
                "content": [
                    [
                        "type": "tool_use", "id": "t-\(command.hashValue)", "name": "Bash",
                        "input": ["command": command],
                    ]
                ],
            ],
        ])
    }

    private static func toolResult(_ text: String) -> String {
        json([
            "type": "user",
            "toolUseResult": ["stdout": text],
            "message": [
                "role": "user",
                "content": [["type": "tool_result", "tool_use_id": "t1", "content": text]],
            ],
        ])
    }

    private static func caveat() -> String {
        json([
            "type": "user",
            "isMeta": true,
            "message": [
                "role": "user",
                "content": "Caveat: The messages below were generated by the user",
            ],
        ])
    }

    private static func queued(_ text: String) -> String {
        json(["type": "queue-operation", "operation": "enqueue", "content": text])
    }

    private static func write(_ lines: [String], terminated: Bool = true) throws -> (
        path: String, offsets: [Int]
    ) {
        let directory = FileManager.default.temporaryDirectory
            .appendingPathComponent("transcript-window-\(UUID().uuidString)")
        try FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true)
        let path = directory.appendingPathComponent("session.jsonl").path

        var body = ""
        var offsets: [Int] = []
        for (i, line) in lines.enumerated() {
            offsets.append(body.utf8.count)
            body += line
            if terminated || i < lines.count - 1 { body += "\n" }
        }
        try body.write(toFile: path, atomically: true, encoding: .utf8)
        return (path, offsets)
    }

    private static func append(_ lines: [String], to path: String, terminated: Bool = true) throws {
        var body = lines.joined(separator: "\n")
        if terminated { body += "\n" }
        let handle = FileHandle(forWritingAtPath: path)!
        defer { try? handle.close() }
        handle.seekToEndOfFile()
        handle.write(body.data(using: .utf8)!)
    }

    // MARK: - readTail

    @Test("a queued prompt shows once after it is delivered")
    func deliveredQueuedPromptShowsOnce() async throws {
        let (path, _) = try Self.write([
            Self.queued("run the check"),
            Self.user("run the check"),
            Self.assistant("done"),
            Self.queued("still waiting"),
        ])
        defer { try? FileManager.default.removeItem(atPath: path) }

        let tail = try await TranscriptReader.readTail(from: path)
        #expect(tail.turns.map(\.textPreview) == ["run the check", "done", "still waiting"])
        #expect(tail.turns.map(\.isQueued) == [false, false, true])
    }

    @Test("a bounded tail is the end of the unbounded one")
    func tailWindowMatchesFullRead() async throws {
        let (path, _) = try Self.write([
            Self.user("one"), Self.assistant("a1"), Self.user("two"),
            Self.assistant("a2"), Self.user("three"), Self.assistant("a3"),
        ])
        defer { try? FileManager.default.removeItem(atPath: path) }

        let full = try await TranscriptReader.readTail(from: path, maxTurns: Int.max)
        let window = try await TranscriptReader.readTail(from: path, maxTurns: 3)

        #expect(!window.hasMore == false)
        #expect(window.turns.map(\.lineNumber) == full.turns.suffix(3).map(\.lineNumber))
        #expect(window.turns.map(\.textPreview) == full.turns.suffix(3).map(\.textPreview))
        #expect(full.hasMore == false)
    }

    @Test("offsets are real file offsets")
    func offsetsAreFileOffsets() async throws {
        let (path, offsets) = try Self.write([
            Self.user("one"), Self.assistant("a1"), Self.user("two"),
        ])
        defer { try? FileManager.default.removeItem(atPath: path) }

        let read = try await TranscriptReader.readTail(from: path)
        #expect(read.turns.map(\.lineNumber) == offsets)
    }

    @Test("a caveat line becomes no turn and breaks no merge")
    func caveatSkippedInsideMerge() async throws {
        let (path, _) = try Self.write([
            Self.user("go"), Self.assistant("part one"), Self.caveat(),
            Self.assistant("part two"),
        ])
        defer { try? FileManager.default.removeItem(atPath: path) }

        let read = try await TranscriptReader.readTail(from: path)
        #expect(read.turns.count == 2)
        #expect(read.turns[1].contentBlocks.count == 2)
    }

    @Test("the tail read reports where complete lines end")
    func fileEndTracksLastNewline() async throws {
        let (path, _) = try Self.write([Self.user("one"), Self.assistant("a1")])
        defer { try? FileManager.default.removeItem(atPath: path) }
        let size = try (FileManager.default.attributesOfItem(atPath: path)[.size] as? Int) ?? 0

        let read = try await TranscriptReader.readTail(from: path)
        #expect(read.fileEnd == size)

        try Self.append(["{\"type\":\"assis"], to: path, terminated: false)
        let partial = try await TranscriptReader.readTail(from: path)
        #expect(partial.fileEnd == size)
        #expect(partial.turns.count == read.turns.count)
    }

    // MARK: - readAppended

    @Test("appended lines splice into the same window a full read gives")
    func appendedSpliceMatchesFullRead() async throws {
        let (path, _) = try Self.write([
            Self.user("go"), Self.assistant("thinking part"),
        ])
        defer { try? FileManager.default.removeItem(atPath: path) }
        let before = try await TranscriptReader.readTail(from: path)

        // The response continues the same merged turn, then a result and a
        // fresh user message arrive.
        try Self.append(
            [Self.assistantTool("ls"), Self.toolResult("files"), Self.user("thanks")], to: path)

        let lastStart = before.turns.last!.lineNumber
        let appended = try #require(
            try await TranscriptReader.readAppended(from: path, startOffset: lastStart))
        let spliced = TranscriptWindow.splice(
            turns: before.turns, reparsedFrom: lastStart, with: appended.turns)

        let full = try await TranscriptReader.readTail(from: path)
        #expect(spliced.map(\.lineNumber) == full.turns.map(\.lineNumber))
        #expect(spliced.map(\.contentBlocks.count) == full.turns.map(\.contentBlocks.count))
        #expect(appended.fileEnd == full.fileEnd)
        // The grown turn keeps its name: the merge starts at the same line.
        #expect(spliced[1].lineNumber == before.turns[1].lineNumber)
        #expect(spliced[1].contentBlocks.count == 2)
    }

    @Test("an unfinished line is not a turn until its newline lands")
    func partialAppendIgnoredThenPickedUp() async throws {
        let (path, _) = try Self.write([Self.user("go"), Self.assistant("done")])
        defer { try? FileManager.default.removeItem(atPath: path) }
        let before = try await TranscriptReader.readTail(from: path)
        let lastStart = before.turns.last!.lineNumber

        let whole = Self.user("next message")
        let cut = String(whole.prefix(30))
        try Self.append([cut], to: path, terminated: false)
        let mid = try #require(
            try await TranscriptReader.readAppended(from: path, startOffset: lastStart))
        #expect(mid.turns.count == 1)

        try Self.append([String(whole.dropFirst(30))], to: path)
        let after = try #require(
            try await TranscriptReader.readAppended(from: path, startOffset: lastStart))
        #expect(after.turns.count == 2)
        #expect(after.turns.last?.textPreview == "next message")
    }

    /// The watcher fires for writes that add no displayable line, and the
    /// splice for one must reproduce the window value for value, so nothing
    /// downstream sees a change that did not happen.
    @Test("a splice that changes nothing produces the very same window")
    func spliceIsIdempotent() async throws {
        let (path, _) = try Self.write([Self.user("go"), Self.assistant("done")])
        defer { try? FileManager.default.removeItem(atPath: path) }
        let before = try await TranscriptReader.readTail(from: path)
        let lastStart = before.turns.last!.lineNumber

        let appended = try #require(
            try await TranscriptReader.readAppended(from: path, startOffset: lastStart))
        let spliced = TranscriptWindow.splice(
            turns: before.turns, reparsedFrom: lastStart, with: appended.turns)

        #expect(spliced == before.turns)
    }

    @Test("reindexing keeps order comparable across a splice")
    func spliceKeepsIndicesAscending() async throws {
        let (path, _) = try Self.write([Self.user("one"), Self.assistant("a"), Self.user("two")])
        defer { try? FileManager.default.removeItem(atPath: path) }
        let before = try await TranscriptReader.readTail(from: path)

        try Self.append([Self.assistant("reply"), Self.user("three")], to: path)
        let lastStart = before.turns.last!.lineNumber
        let appended = try #require(
            try await TranscriptReader.readAppended(from: path, startOffset: lastStart))
        let spliced = TranscriptWindow.splice(
            turns: before.turns, reparsedFrom: lastStart, with: appended.turns)

        let indices = spliced.map(\.index)
        #expect(indices == indices.sorted())
        #expect(Set(indices).count == indices.count)
    }

    // MARK: - findPreviousTypedUserTurn

    @Test("the scan passes over everything nobody typed")
    func previousTypedSkipsMachinery() async throws {
        let (path, offsets) = try Self.write([
            Self.user("the real question"),
            Self.assistantTool("make build"),
            Self.toolResult("built"),
            Self.user("✓ Agent \"Build\" finished"),
            Self.user("[Request interrupted by user]"),
            Self.caveat(),
            Self.assistant("summary"),
            Self.user("current message"),
        ])
        defer { try? FileManager.default.removeItem(atPath: path) }

        let found = try #require(
            try await TranscriptReader.findPreviousTypedUserTurn(in: path, before: offsets[7]))
        #expect(found.turn.lineNumber == offsets[0])
        #expect(found.turn.textPreview == "the real question")
        #expect(found.endOffset == offsets[1])
    }

    @Test("a prompt sent through the queue counts as typed")
    func previousTypedFindsQueuedPrompt() async throws {
        let (path, offsets) = try Self.write([
            Self.queued("queued prompt"),
            Self.assistant("working"),
            Self.user("now"),
        ])
        defer { try? FileManager.default.removeItem(atPath: path) }

        let found = try #require(
            try await TranscriptReader.findPreviousTypedUserTurn(in: path, before: offsets[2]))
        #expect(found.turn.lineNumber == offsets[0])
    }

    @Test("nothing typed above reports nothing")
    func previousTypedNilAtHead() async throws {
        let (path, offsets) = try Self.write([
            Self.assistant("preamble"), Self.toolResult("noise"), Self.user("first"),
        ])
        defer { try? FileManager.default.removeItem(atPath: path) }

        let found = try await TranscriptReader.findPreviousTypedUserTurn(
            in: path, before: offsets[2])
        #expect(found == nil)
    }

    @Test("the scan crosses chunk boundaries through a huge tool result")
    func previousTypedCrossesChunks() async throws {
        // Larger than the 1MB scan chunk, so the target line and the scan
        // start sit in different chunks with a line spanning the boundary.
        let huge = String(repeating: "x", count: (1 << 20) + 4096)
        let (path, offsets) = try Self.write([
            Self.user("far above"),
            Self.toolResult(huge),
            Self.user("current"),
        ])
        defer { try? FileManager.default.removeItem(atPath: path) }

        let found = try #require(
            try await TranscriptReader.findPreviousTypedUserTurn(in: path, before: offsets[2]))
        #expect(found.turn.lineNumber == offsets[0])
    }

    // MARK: - countVisibleTurns and readRange

    @Test("the count is the number of rows expanding the range draws")
    func countMatchesRangeRead() async throws {
        let (path, offsets) = try Self.write([
            Self.user("start"),
            Self.assistant("part a"), Self.assistant("part b"),  // one merged row
            Self.assistantTool("ls"), Self.toolResult("out"),  // one row + invisible
            Self.assistantTool("pwd"), Self.toolResult("out2"),  // one row + invisible
            Self.caveat(),  // nothing
            Self.user("end"),
        ])
        defer { try? FileManager.default.removeItem(atPath: path) }

        let start = offsets[1]
        let end = offsets[8]
        let count = try await TranscriptReader.countVisibleTurns(
            from: path, startOffset: start, endOffset: end)
        let range = try await TranscriptReader.readRange(
            from: path, startOffset: start, endOffset: end)

        #expect(count == range.turns.count(where: \.hasVisibleChatContent))
        #expect(range.consumedEnd == end)
        // part a, part b and the first tool call are consecutive assistant
        // lines, so they merge into one row; the tool result in between
        // gives the second call a row of its own.
        #expect(count == 2)
    }

    @Test("a paged range read resumes exactly where it stopped")
    func rangeReadPagesCleanly() async throws {
        var lines: [String] = []
        for i in 0..<12 {
            lines.append(Self.user("message \(i)"))
            lines.append(Self.assistant("reply \(i)"))
        }
        let (path, offsets) = try Self.write(lines)
        defer { try? FileManager.default.removeItem(atPath: path) }
        let end = offsets.last! // range covers everything but the final line

        let firstPage = try await TranscriptReader.readRange(
            from: path, startOffset: 0, endOffset: end, maxVisible: 5)
        #expect(firstPage.turns.count(where: \.hasVisibleChatContent) == 5)
        #expect(firstPage.consumedEnd < end)

        let rest = try await TranscriptReader.readRange(
            from: path, startOffset: firstPage.consumedEnd, endOffset: end)
        let whole = try await TranscriptReader.readRange(
            from: path, startOffset: 0, endOffset: end)
        #expect(
            (firstPage.turns + rest.turns).map(\.lineNumber) == whole.turns.map(\.lineNumber))
    }

    // MARK: - readAround region

    @Test("the window around a match reports the bytes it consumed")
    func readAroundReportsRegion() async throws {
        let lines = (0..<20).map { Self.user("message \($0)") }
        let (path, offsets) = try Self.write(lines)
        defer { try? FileManager.default.removeItem(atPath: path) }

        let around = try await TranscriptReader.readAround(
            from: path, byteOffset: offsets[10], before: 3, after: 3)

        #expect(around.turns.count == 6)
        #expect(around.regionStart == offsets[7])
        #expect(around.regionEnd == offsets[13])
        #expect(around.turns.allSatisfy {
            $0.lineNumber >= around.regionStart && $0.lineNumber < around.regionEnd
        })
    }

    // MARK: - TranscriptWindow math

    private static func turn(_ offset: Int, role: String = "user") -> ConversationTurn {
        ConversationTurn(
            index: offset, lineNumber: offset, role: role, textPreview: "t\(offset)",
            contentBlocks: [ContentBlock(kind: .text, text: "t\(offset)")]
        )
    }

    @Test("merging keeps file order and the loaded copy of a turn")
    func mergeKeepsOrderAndLoadedCopies() {
        let loaded = [Self.turn(10), Self.turn(50)]
        let arriving = [
            Self.turn(30),
            ConversationTurn(index: 0, lineNumber: 50, role: "user", textPreview: "stale"),
        ]

        let merged = TranscriptWindow.merge(turns: loaded, inserting: arriving)

        #expect(merged.map(\.lineNumber) == [10, 30, 50])
        #expect(merged[2].textPreview == "t50")
    }

    @Test("a parsed region cuts collapsed ranges into what is still hidden")
    func subtractSplitsRanges() {
        let ranges = [
            CollapsedTurnRange(startOffset: 0, endOffset: 100, messageCount: 5),
            CollapsedTurnRange(startOffset: 200, endOffset: 600, messageCount: 40),
            CollapsedTurnRange(startOffset: 700, endOffset: 800, messageCount: 3),
        ]

        let (kept, toRecount) = TranscriptWindow.subtract(region: 300..<500, from: ranges)

        #expect(kept.map(\.startOffset) == [0, 700])
        #expect(toRecount.map { [$0.startOffset, $0.endOffset] } == [[200, 300], [500, 600]])
    }

    @Test("a region swallowing a range leaves nothing to recount")
    func subtractSwallowsRange() {
        let ranges = [CollapsedTurnRange(startOffset: 200, endOffset: 300, messageCount: 4)]

        let (kept, toRecount) = TranscriptWindow.subtract(region: 100..<400, from: ranges)

        #expect(kept.isEmpty)
        #expect(toRecount.isEmpty)
    }
}
